<template>
  <q-page class="q-pa-sm">
    <CompanyBanner class="q-mb-sm"/>
    <div class="row items-center q-mb-sm"><div><div class="text-subtitle1 text-weight-bold">Nueva compra</div><div class="text-caption text-grey-7">Agrega mercadería al inventario</div></div><q-space/><q-btn flat dense icon="groups" label="Proveedores" no-caps to="/proveedores"/><q-btn flat dense icon="shopping_bag" label="Ver compras" no-caps to="/compras"/></div>
    <div class="row q-col-gutter-sm">
      <div class="col-12 col-lg-7">
        <q-card flat bordered>
          <q-card-section class="row q-col-gutter-sm q-pa-sm"><q-input ref="searchInput" v-model="search" dense outlined autofocus clearable debounce="250" class="col" placeholder="Buscar o escanear producto" @update:model-value="loadProducts" @keydown.enter.prevent="addExact"><template #prepend><q-icon name="qr_code_scanner"/></template></q-input></q-card-section>
          <q-separator/><q-card-section class="q-pa-sm product-grid"><q-card v-for="product in products" :key="product.id" flat bordered class="product-card cursor-pointer" @click="add(product)"><div class="product-image"><img v-if="product.foto" :src="photoUrl(product.foto)"/><q-icon v-else name="inventory_2" size="30px" color="grey-4"/></div><q-card-section class="q-pa-xs"><div class="text-weight-bold ellipsis-2-lines product-name">{{product.nombre}}</div><div class="product-meta text-grey-7">{{product.codigo}} · {{product.unidad}}</div><div class="row items-center product-meta"><b class="text-primary">Bs {{money(product.precio_compra)}}</b><q-space/><span>Stock {{qty(product.stock_inicial,product.unidad)}}</span></div></q-card-section></q-card></q-card-section>
        </q-card>
      </div>
      <div class="col-12 col-lg-5">
        <q-card flat bordered class="purchase-card"><q-card-section class="row items-center q-py-sm"><q-icon name="shopping_cart" color="primary" size="22px" class="q-mr-xs"/><b>Productos de la compra</b><q-space/><q-badge color="primary" :label="items.length"/></q-card-section><q-separator/>
          <q-list v-if="items.length" separator class="item-list"><q-item v-for="item in items" :key="item.id" dense class="purchase-item q-px-xs"><div class="purchase-row full-width"><div class="purchase-product" :title="item.nombre"><div class="purchase-product-name">{{item.nombre}}</div><div class="purchase-product-unit">{{item.unidad}}</div></div><label class="compact-field"><span>Cant.</span><input v-model.number="item.cantidad" class="qty-input" type="number" min="0.001" step="0.001" @input="syncItemTotal(item)"></label><label class="compact-field"><span>Costo</span><input v-model.number="item.precio_unitario" class="price-input" type="number" min="0" step="0.0001" @input="syncItemTotal(item)"></label><label class="compact-field"><span>Total</span><input v-model.number="item.total_editable" class="total-input" type="number" min="0" step="0.01" @blur="applyItemTotal(item)"></label><label class="compact-field"><span>Lote</span><input v-model="item.lote" class="lot-input" placeholder="—"></label><label class="compact-field expiry-field"><span>Vence</span><input v-model="item.fecha_vencimiento" class="date-input" type="date"></label><q-btn dense flat round size="xs" icon="delete" color="negative" @click="remove(item)"/></div></q-item></q-list>
          <q-card-section v-else class="text-center text-grey-6 q-py-lg">Agrega productos</q-card-section><q-separator/><q-card-section class="row text-h6 text-primary"><b>Total</b><q-space/><b>Bs {{money(total)}}</b></q-card-section><q-card-actions class="q-pa-sm"><q-btn class="full-width" color="positive" unelevated icon="save" label="Guardar compra" no-caps :disable="!items.length" @click="openPurchaseDialog"/></q-card-actions>
        </q-card>
      </div>
    </div>
    <q-dialog v-model="quantityDialog"><q-card style="width:390px;max-width:94vw"><q-form @submit.prevent="confirmAdd"><q-card-section class="row items-center q-pb-sm"><div><div class="text-subtitle1 text-weight-bold">Agregar producto</div><div class="text-caption text-grey-7">{{selectedProduct?.nombre}}</div></div><q-space/><q-btn flat round dense icon="close" v-close-popup/></q-card-section><q-card-section class="q-pt-none"><q-input ref="quantityInput" v-model.number="addQuantity" autofocus outlined type="number" :min="selectedProduct?.unidad==='KG'?0.001:1" :step="selectedProduct?.unidad==='KG'?0.001:1" label="Cantidad" suffix="" :hint="selectedProduct?.unidad"/></q-card-section><q-card-actions align="right"><q-btn flat label="Cancelar" v-close-popup/><q-btn color="primary" icon="add_shopping_cart" label="Agregar" type="submit"/></q-card-actions></q-form></q-card></q-dialog>
    <q-dialog v-model="purchaseDialog"><q-card style="width:960px;max-width:96vw"><q-card-section class="row items-center"><div><div class="text-h6">Confirmar compra</div><div class="text-caption text-grey-7">Revisa los productos y completa los datos</div></div><q-space/><q-btn flat round dense icon="close" v-close-popup/></q-card-section><q-separator/><q-card-section class="q-pa-sm"><div class="row q-col-gutter-sm"><div class="col-12 col-md-6"><div class="row q-col-gutter-xs"><q-select v-model="provider" :options="providers" option-label="nombre" dense outlined label="Proveedor *" class="col"/><q-btn dense flat round color="primary" icon="person_add" @click="providerDialog=true"/></div></div><q-input v-model="invoice" dense outlined label="Número de factura" class="col-12 col-md-3"/><q-select v-model="paymentType" :options="paymentTypes" dense outlined label="Tipo de pago *" class="col-12 col-md-3"/><template v-if="paymentType==='COMBINADO'"><q-input v-model.number="cashAmount" dense outlined type="number" min="0" step="0.01" label="Monto efectivo" prefix="Bs" class="col-6 col-md-3"/><q-input v-model.number="qrAmount" dense outlined type="number" min="0" step="0.01" label="Monto QR" prefix="Bs" class="col-6 col-md-3"/><div class="col-12 col-md-3 text-caption self-center" :class="paymentDifference===0?'text-positive':'text-negative'">Diferencia: Bs {{money(paymentDifference)}}</div></template><q-input v-model="comment" dense outlined label="Comentario" class="col-12"/></div></q-card-section><q-separator/><q-card-section class="q-pa-none final-table-wrap"><q-markup-table dense flat separator="horizontal"><thead><tr><th class="text-left">Producto</th><th class="text-right">Cantidad</th><th class="text-right">Costo</th><th class="text-right">Total</th><th class="text-left">Lote</th><th class="text-left">Vencimiento</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{item.nombre}}</td><td class="text-right">{{qty(item.cantidad,item.unidad)}} {{item.unidad}}</td><td class="text-right">Bs {{money(item.precio_unitario)}}</td><td class="text-right text-weight-bold">Bs {{money(item.total_editable)}}</td><td>{{item.lote||'—'}}</td><td>{{item.fecha_vencimiento||'—'}}</td></tr></tbody></q-markup-table></q-card-section><q-separator/><q-card-section class="row items-center text-h6 text-primary"><b>Total</b><q-space/><b>Bs {{money(total)}}</b></q-card-section><q-card-actions align="right"><q-btn flat label="Volver" v-close-popup/><q-btn color="positive" unelevated icon="save" label="Confirmar y guardar" :loading="saving" @click="save"/></q-card-actions></q-card></q-dialog>
    <q-dialog v-model="providerDialog"><q-card style="width:460px;max-width:94vw"><q-form @submit="saveProvider"><q-card-section class="row"><b>Nuevo proveedor</b><q-space/><q-btn flat round dense icon="close" v-close-popup/></q-card-section><q-card-section class="q-gutter-sm"><q-input v-model="providerForm.nombre" dense outlined label="Nombre *"/><q-input v-model="providerForm.nit" dense outlined label="NIT"/><q-input v-model="providerForm.telefono" dense outlined label="Teléfono"/><q-input v-model="providerForm.direccion" dense outlined label="Dirección"/></q-card-section><q-card-actions align="right"><q-btn flat label="Cancelar" v-close-popup/><q-btn color="primary" label="Guardar" type="submit" :loading="providerSaving"/></q-card-actions></q-form></q-card></q-dialog>
  </q-page>
</template>
<script setup>
import { computed, getCurrentInstance, onMounted, reactive, ref, watch } from 'vue'
import { printPurchase } from '../../addons/compraPrint'
import CompanyBanner from '../../components/CompanyBanner.vue'
const {proxy}=getCurrentInstance(),products=ref([]),providers=ref([]),items=ref([]),search=ref(''),provider=ref(null),invoice=ref(''),comment=ref(''),paymentType=ref('EFECTIVO'),cashAmount=ref(0),qrAmount=ref(0),saving=ref(false),providerSaving=ref(false),searchInput=ref(null),providerDialog=ref(false),quantityDialog=ref(false),purchaseDialog=ref(false),selectedProduct=ref(null),addQuantity=ref(1),quantityInput=ref(null)
const paymentTypes=['EFECTIVO','QR','COMBINADO'],providerForm=reactive({nombre:'',nit:'',telefono:'',direccion:''})
const photoUrl=path=>`${proxy.$imgBase}/images/${path}`,money=v=>Number(v||0).toFixed(2),qty=(v,u)=>Number(v||0).toFixed(u==='KG'?3:0),lineTotal=i=>Number(i.cantidad||0)*Number(i.precio_unitario||0),total=computed(()=>items.value.reduce((s,i)=>s+Number(i.total_editable||0),0))
const paymentDifference=computed(()=>Number((total.value-(Number(cashAmount.value)||0)-(Number(qrAmount.value)||0)).toFixed(2)))
watch([paymentType,total],()=>{if(paymentType.value==='EFECTIVO'){cashAmount.value=total.value;qrAmount.value=0}else if(paymentType.value==='QR'){cashAmount.value=0;qrAmount.value=total.value}else if(Number(cashAmount.value)+Number(qrAmount.value)===0){cashAmount.value=total.value;qrAmount.value=0}})
const daysUntil=value=>Math.ceil((new Date(`${value}T12:00:00`)-new Date())/86400000),expiryLabel=value=>daysUntil(value)<0?`Vencido hace ${Math.abs(daysUntil(value))} días`:`Vence en ${daysUntil(value)} días`
function loadProducts(){proxy.$axios.get('/productos',{params:{q:search.value,per_page:0}}).then(r=>products.value=r.data.data)}
function loadProviders(){proxy.$axios.get('/proveedores').then(r=>providers.value=r.data)}
function add(p,quantity=1){selectedProduct.value=p;addQuantity.value=quantity;quantityDialog.value=true}
function confirmAdd(){const p=selectedProduct.value,quantity=Number(addQuantity.value);if(!p||quantity<=0)return proxy.$alert.error('Ingrese una cantidad válida');const normalized=p.unidad==='KG'?Math.round(quantity*1000)/1000:Math.floor(quantity);if(normalized<=0)return proxy.$alert.error('Ingrese una cantidad válida');const existing=items.value.find(i=>i.id===p.id);if(existing){existing.cantidad=Number((Number(existing.cantidad)+normalized).toFixed(3));syncItemTotal(existing)}else items.value.push({...p,cantidad:normalized,precio_unitario:Number(p.precio_compra),total_editable:(Number(p.precio_compra)*normalized).toFixed(2),lote:'',fecha_vencimiento:''});quantityDialog.value=false;selectedProduct.value=null;searchInput.value?.focus()}
async function addExact(){const q=String(search.value||'').trim();const scale=/^2\d{12}$/.test(q)?{code:q.slice(0,7),weight:Number(q.slice(7,12))/1000}:null;if(scale){const {data}=await proxy.$axios.get('/productos',{params:{q:scale.code,per_page:0}});const p=data.data.find(i=>i.codigo===scale.code||i.codigo_barras===scale.code);if(p){add(p,p.unidad==='KG'?scale.weight:1);search.value='';loadProducts()}return}const p=products.value.find(i=>i.codigo===q||i.codigo_barras===q);if(p){add(p);search.value='';loadProducts()}}
function remove(i){items.value=items.value.filter(x=>x.id!==i.id)}
function syncItemTotal(item){item.total_editable=(Number(item.cantidad||0)*Number(item.precio_unitario||0)).toFixed(2)}
function applyItemTotal(item){const quantity=Number(item.cantidad||0),value=Math.max(0,Number(item.total_editable)||0);item.total_editable=value.toFixed(2);if(quantity>0)item.precio_unitario=Number((value/quantity).toFixed(4))}
function saveProvider(){if(!providerForm.nombre)return proxy.$alert.error('Ingrese el nombre');providerSaving.value=true;proxy.$axios.post('/proveedores',providerForm).then(r=>{providers.value.push(r.data);provider.value=r.data;providerDialog.value=false;Object.assign(providerForm,{nombre:'',nit:'',telefono:'',direccion:''});proxy.$alert.success('Proveedor guardado')}).catch(e=>proxy.$alert.error(Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||'No se pudo guardar el proveedor')).finally(()=>providerSaving.value=false)}
function openPurchaseDialog(){if(items.value.some(i=>Number(i.cantidad)<=0))return proxy.$alert.error('Revise las cantidades');purchaseDialog.value=true}
function save(){if(!provider.value)return proxy.$alert.error('Seleccione un proveedor');if(items.value.some(i=>Number(i.cantidad)<=0))return proxy.$alert.error('Revise las cantidades');if(paymentType.value==='COMBINADO'&&paymentDifference.value!==0)return proxy.$alert.error('Efectivo y QR deben sumar el total');saving.value=true;proxy.$axios.post('/compras',{proveedor_id:provider.value.id,numero_factura:invoice.value,tipo_pago:paymentType.value,monto_efectivo:cashAmount.value,monto_qr:qrAmount.value,comentario:comment.value,detalles:items.value.map(i=>({producto_id:i.id,cantidad:i.cantidad,precio_unitario:i.precio_unitario,lote:i.lote||null,fecha_vencimiento:i.fecha_vencimiento||null}))}).then(r=>{proxy.$alert.success(`Compra ${r.data.numero} registrada`);printPurchase(r.data);purchaseDialog.value=false;items.value=[];provider.value=null;invoice.value='';comment.value='';paymentType.value='EFECTIVO';loadProducts();searchInput.value?.focus()}).catch(e=>proxy.$alert.error(Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||'No se pudo guardar')).finally(()=>saving.value=false)}
onMounted(()=>{loadProducts();loadProviders()})
</script>
<style scoped>
.product-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(118px,1fr));gap:5px;max-height:calc(100vh - 160px);overflow:auto}.product-card{overflow:hidden}.product-card:hover{border-color:#f57c00;background:#fffaf5}.product-image{height:58px;background:#fffaf3;display:flex;align-items:center;justify-content:center}.product-image img{width:100%;height:100%;object-fit:contain}.product-name{height:30px;font-size:11px;line-height:15px}.product-meta{font-size:9px;line-height:13px;white-space:nowrap;overflow:hidden}.purchase-card{position:sticky;top:62px}.item-list{max-height:calc(100vh - 250px);min-height:240px;overflow:auto}.purchase-item{min-height:44px;padding-top:3px;padding-bottom:3px}.purchase-row{display:flex;align-items:center;gap:3px;min-width:0}.purchase-product{flex:1 1 110px;min-width:72px;overflow:hidden}.purchase-product-name{font-size:10px;font-weight:600;line-height:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.purchase-product-unit{font-size:8px;color:#78909c;line-height:10px}.compact-field{flex:0 0 auto;font-size:8px;line-height:9px;color:#607d8b;text-align:center}.compact-field span{display:block}.qty-input,.price-input,.total-input,.lot-input,.date-input{height:22px;border:1px solid #cfd8dc;border-radius:4px;padding:1px 3px;font-size:10px;color:#263238;background:#fff;text-align:right}.qty-input{width:45px}.price-input{width:55px}.total-input{width:58px;font-weight:700;color:#f57c00}.lot-input{width:52px;text-align:left}.date-input{width:94px;font-size:9px}.qty-input:focus,.price-input:focus,.total-input:focus,.lot-input:focus,.date-input:focus{outline:1px solid #f57c00;border-color:#f57c00}.final-table-wrap{max-height:42vh;overflow:auto}@media(max-width:1023px){.purchase-card{position:static}.product-grid{max-height:none}.item-list{max-height:55vh}}@media(max-width:599px){.purchase-row{gap:2px;overflow-x:auto}.purchase-product{min-width:68px}.expiry-field{display:none}}
</style>
